name: PHP-CS-Fixer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify your project's PHP version
          extensions: mbstring, json
          tools: composer, cs2pr

      # Step 3: Install dependencies
      - name: Install dependencies
        run: composer global require friendsofphp/php-cs-fixer --prefer-dist

      # Step 4: Run PHP-CS-Fixer
      - name: Run PHP-CS-Fixer
        run: ~/.composer/vendor/bin/php-cs-fixer fix .

      # Step 5: Commit the changes
      - name: Commit the changes
        run: |
          git config --global user.email " [email protected]"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Apply PHP-CS-Fixer rules"
          git push